version: "3.3"

services:
  eureka-service:
    hostname: ${EUREKA_HOST}
    build: modules/eureka-service/
    networks:
      - contest

  problem-service:
    build: modules/problem-service/
    networks:
      - contest
    env_file:
      - .env
    depends_on:
      - eureka-service
      - contest-postgres

  account-service:
    build: modules/account-service/
    networks:
      - contest
    env_file:
      - .env
    depends_on:
      - eureka-service
      - mongo

  solution-service:
    build: modules/solution-service/
    networks:
      - contest
    env_file:
      - .env
    depends_on:
      - eureka-service
      - contest-postgres

  test-executor-service:
    build: modules/test-executor-service/
    networks:
      - contest
    env_file:
      - .env
    volumes:
      - ./scripts/script.sh:/scripts/script.sh
    depends_on:
      - eureka-service
      - problem-service
      - solution-service
      - rabbitmq

  gateway-service:
    build: modules/graphql-api-gateway/
    networks:
      - contest
    env_file:
      - .env
    ports:
      - "8341:8341"
    depends_on:
      - eureka-service
      - rabbitmq
      - problem-service
      - solution-service
      - test-executor-service
      - account-service

  contest-postgres:
    hostname: ${POSTGRES_HOST}
    image: postgres:12.3-alpine
    ports:
      - "5438:5432"
    networks:
      - contest
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/
      - ./volumes/postgresql:/var/lib/postgresql/data
    env_file:
      - .env


  mongo:
    image: mongo
    restart: always
    hostname: ${MONGO_HOST}
#    ports:
#      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - contest
    volumes:
      - ./volumes/mongo:/data/db
#
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - "8379:8081"
#    environment:
#      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST}
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#    networks:
#      - contest

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: ${RABBIT_HOST}
    networks:
      - contest


networks:
  contest:
    driver: bridge


