server:
  port: 8081

spring:
  r2dbc:
    name: ${PROBLEM_DB_NAME:contest}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: r2dbc:postgresql://${PROBLEM_DB_HOST:localhost}
  liquibase:
    url: jdbc:postgresql://${PROBLEM_DB_HOST:localhost}:${PROBLEM_DB_PORT:5432}/${PROBLEM_DB_NAME:contest}
    change-log: db/changelog/db.changelog-master.yaml
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PROBLEM_DB_HOST:localhost}:${PROBLEM_DB_PORT:5432}/${PROBLEM_DB_NAME:contest}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  application:
    name: problem-service

jwt:
  expiration: 15m
  secret: ${JWT_SECRET}
#logging:
#  level:
#    root: trace

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
