server:
  port: 8084

spring:
  application:
    name: account-service
  r2dbc:
    name: ${ACCOUNT_DB_NAME:contest_user}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: r2dbc:postgresql://${ACCOUNT_DB_HOST:localhost}
  liquibase:
    url: jdbc:postgresql://${ACCOUNT_DB_HOST:localhost}:${ACCOUNT_DB_PORT:5432}/${ACCOUNT_DB_NAME:contest_user}
    change-log: db/changelog/db.changelog-master.yaml
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${ACCOUNT_DB_HOST:localhost}:${ACCOUNT_DB_PORT:5432}/${ACCOUNT_DB_NAME:contest_user}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

#    mongodb:
#      authentication-database: contest_user
#      host: ${MONGO_HOST:localhost}
#      port: 27017
#      username: contest1
#      password: asd123
#      database: contest_user
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5



jwt:
  expiration: 15m
  secret: ${JWT_SECRET}

refresh-token:
  expiration: 24h
#logging:
#  level:
#    root: trace
