#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE $PROBLEM_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $PROBLEM_DB_NAME TO $POSTGRES_USER;
EOSQL

