server:
  port: 8341

spring:
  application:
    name: gateway-api
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: guest
    password: guest
    listener:
      direct:
        prefetch: 1

graphql:
  packages: com.uolken

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
